# Generated by Django 2.0.1 on 2018-02-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PgFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pg_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pg_gst', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
