# Generated by Django 2.0.1 on 2018-02-22 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0002_pgfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgfile',
            name='store_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commission.OcStorelocatorStore'),
        ),
    ]
