# Generated by Django 2.0.1 on 2018-02-23 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0003_pgfile_store_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GstStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstno', models.CharField(max_length=100, null=True)),
                ('store_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commission.OcStorelocatorStore')),
            ],
        ),
    ]
