# Generated by Django 2.0.1 on 2018-01-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_file', models.FileField(upload_to='documents/')),
                ('ebazr_file', models.FileField(upload_to='documents/')),
                ('vendor_file', models.FileField(upload_to='documents/')),
                ('result_file', models.FileField(null=True, upload_to='documents/')),
                ('basemap_file', models.FileField(null=True, upload_to='documents/')),
            ],
        ),
    ]
