# Generated by Django 2.0.1 on 2018-01-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0002_auto_20180120_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='base_file',
            field=models.FileField(upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='results',
            name='basemap_file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='results',
            name='ebazr_file',
            field=models.FileField(upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='results',
            name='result_file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='results',
            name='vendor_file',
            field=models.FileField(upload_to='files/'),
        ),
    ]
