# Generated by Django 2.0.1 on 2018-02-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0003_auto_20180120_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=1023, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
            ],
        ),
    ]
