# Generated by Django 2.0.1 on 2018-02-05 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0004_defaultrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcessionalRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FLAT PER ORDER', 'FLAT PER ORDER'), ('FLAT PER SKU', 'FLAT PER SKU')], max_length=100)),
                ('store_name', models.CharField(max_length=1023)),
                ('sku', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('date_from', models.IntegerField()),
                ('date_to', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=1023, null=True)),
                ('delivered_by', models.CharField(choices=[('STORE', 'STORE'), ('EBAZR', 'EBAZR')], max_length=100)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('store_name', models.CharField(max_length=1023, null=True)),
                ('orders', models.IntegerField()),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pincode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=1023, null=True)),
                ('sku', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=1023)),
                ('thres_amt', models.DecimalField(decimal_places=2, max_digits=4)),
                ('amt', models.DecimalField(decimal_places=2, max_digits=4)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='pincodes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapping.Pincode'),
        ),
    ]
