# Generated by Django 2.0.1 on 2018-02-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0005_auto_20180205_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concessionalrate',
            name='date_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='concessionalrate',
            name='date_to',
            field=models.DateField(),
        ),
    ]
