# Generated by Django 2.0.1 on 2018-02-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0009_auto_20180206_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalty_orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('price', models.CharField(max_length=1023, null=True)),
                ('merchant_name', models.CharField(max_length=1023, null=True)),
            ],
        ),
    ]
