# Generated by Django 2.0.1 on 2018-02-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0010_penalty_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalty_orders',
            name='reason',
            field=models.CharField(choices=[('Cancelled By Store', 'Cancelled By Store'), ('Customer Not Available', 'Customer Not Available')], max_length=100, null=True),
        ),
    ]
