# Generated by Django 2.0.1 on 2018-02-08 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0015_auto_20180208_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='concessionalrate',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mapping.OcCategoryDescription'),
        ),
        migrations.AlterField(
            model_name='concessionalrate',
            name='sku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mapping.OcProduct'),
        ),
        migrations.AlterField(
            model_name='concessionalrate',
            name='type',
            field=models.CharField(choices=[('FLAT PER ORDER', 'FLAT PER ORDER'), ('FLAT PER SKU', 'FLAT PER SKU'), ('PERCENTAGE', 'PERCENTAGE'), ('RATE PER CATEGORY', 'RATE PER CATEGORY')], max_length=100),
        ),
    ]
