# Generated by Django 2.0.1 on 2018-02-08 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0016_auto_20180208_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concessionalrate',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mapping.OcCategoryDescription'),
        ),
        migrations.AlterField(
            model_name='concessionalrate',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mapping.OcProduct'),
        ),
    ]
