# Generated by Django 2.0.1 on 2018-02-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0017_auto_20180208_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo',
            name='sku',
        ),
        migrations.AddField(
            model_name='promo',
            name='sku',
            field=models.ManyToManyField(to='mapping.OcProduct'),
        ),
    ]
