# Generated by Django 2.0.1 on 2018-02-08 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0018_auto_20180208_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='penalty',
            old_name='rate',
            new_name='price',
        ),
    ]
