# Generated by Django 2.0.1 on 2018-02-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0019_auto_20180208_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalcommrate',
            name='payment_gateway_pass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='additionalcommrate',
            name='tax_inclusive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='defaultrate',
            name='payment_gateway_pass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='defaultrate',
            name='tax_inclusive',
            field=models.BooleanField(default=False),
        ),
    ]
