# Generated by Django 2.0.1 on 2018-02-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0020_auto_20180208_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo',
            name='sku',
        ),
        migrations.AddField(
            model_name='promo',
            name='sku',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
