# Generated by Django 2.0.1 on 2018-02-09 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0022_auto_20180209_1915'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pincode',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
