# Generated by Django 2.0.1 on 2018-02-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0026_auto_20180212_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalcommrate',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='concessionalrate',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='defaultrate',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='amt',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
