# Generated by Django 2.0.1 on 2018-02-14 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0029_auto_20180214_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='sku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mapping.OcProduct'),
        ),
    ]
